name: Redeem GiftCode

on: 
 workflow_dispatch:
   inputs:
     code:
       type: text
       required: true
       description: 'Giftcode to redeem'

jobs:
  redeem:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - run: |
          npm install
          node ./bin/index.js ${{ github.event.inputs.code }} FMX -d 2000
        name: Redeem code
